### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by mihail-dimitrov** [netmeansnet/NmnMultiUserBundle#17]
Hi, there is an issue with registering user with the same username/email in the different types.

For example:
1. Register user in UserOneType
2. Register user with the same username/email in the same UserOneType - validation works ok (existing user is detected).
3. Register user with the same username/email in UserTwoType - SQLSTATE[23000]: Integrity constraint violation exception

I'm using Symfony 2.1 with the latest FOSUserBundle.

Am I missing something or it's a something that need to be fixed?

Thanks.

**Comment by mihail-dimitrov** [comment]
Hi again.

I just spotted the custom validation solution, described in https://github.com/netmeansnet/NmnMultiUserBundle/issues/9. It fixes the validation problem. It doubles the error message in case 2 (from steps described above), but this I will take care of.

You bundle is a lifesaver for me, as I just don't want to go with the standard users setup.

As a suggestion though, you can possibly add the solution or at least the description of it somewhere in your bundle documentations, as I think it's a general case and will save some time for others to come :)

(Close the issue at your will)

Best regards,
Mihail.

**Comment by leopro** [comment]
hi @mihail-dimitrov thank you for your suggestion ;-)

the bundle was moved under PUGX and you can find a working solution with the same approach of NmnMultiUser (sf2.1 + fosub 1.3) here: https://github.com/PUGX/PUGXMultiUserBundle/tree/1.3 and here the doc https://github.com/PUGX/PUGXMultiUserBundle/blob/1.3/Resources/doc/index.md#3-create-your-userbundle

The master and the branch 1.4 have a new more decoupled approach, maybe you'll like it.

**Comment by mihail-dimitrov** [comment]
Hi @leopro, I was just checking 1.4 actually :)
And yes, it indeed looks better from my point of view. I'm eager to test it :), but I stumbled upon a problem installing it with composer. 
Here are the pretty standard requirements list of my composer.json:

```
"require": {
    "php": ">=5.3.3",
    "symfony/symfony": "2.1.*",
    "doctrine/orm": ">=2.2.3,<2.4-dev",
    "doctrine/doctrine-bundle": "1.0.*",
    "twig/extensions": "1.0.*",
    "symfony/assetic-bundle": "2.1.*",
    "symfony/swiftmailer-bundle": "2.1.*",
    "symfony/monolog-bundle": "2.1.*",
    "sensio/distribution-bundle": "2.1.*",
    "sensio/framework-extra-bundle": "2.1.*",
    "sensio/generator-bundle": "2.1.*",
    "jms/security-extra-bundle": "1.2.*",
    "jms/di-extra-bundle": "1.1.*",

    "friendsofsymfony/user-bundle": "*"
},
```

and both 1.4 ("pugx/multi-user-bundle": "1.4.x-dev") or master ("pugx/multi-user-bundle": "master-dev") failed to be installed because their requirements cannot be resolved.

**Comment by leopro** [comment]
Hi @mihail-dimitrov the 1.4 has a new approach, so you have to modify your code if it is based on NmnMultiUser :-)
Here https://github.com/leopro/PUGXMultiUserSandbox you can find a sandbox; the branch 1.4 is in sync with PUGXMultuìiUser 1.4

**Comment by mihail-dimitrov** [comment]
Great work! The new approach, added validation ...

Thank you very much!

**Comment by leopro** [comment]
@mihail-dimitrov I'm trying to add validation also for old approach, but for now it's does not work :-)
