### ISSUE TITLE
Profile edit action - twig form object fields empty

### ISSUE THREAD

**Issue by gyalamanchi** [netmeansnet/NmnMultiUserBundle#19]
Hello, 

My form fields in editAction are not loading the values when rendered to the twig template based on discriminator.

Here is one of the three Profile controllers:

<?php

namespace MHO\VmpBundle\Controller;

use Nmn\MultiUserBundle\Controller\ProfileController as BaseController;
use Symfony\Component\HttpFoundation\RedirectResponse;

class ProfileVmpPhysicianController extends BaseController
{
    public function editAction()
    {  
        $discriminator = $this->container->get('nmn_user_discriminator');
        $form = $discriminator->getProfileForm();

```
    return $this->container->get('templating')->renderResponse('MHOVmpBundle:Profile:profile_vmp_physician.html.twig', array(
        'form' => $form->createView(),
    ));
}
```

}

Here is one of the three Profile Form type classes:

<?php

namespace MHO\VmpBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;

class ProfileVmpPhysicianFormType extends BaseType
{  
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildUserForm($builder, $options);

```
    $builder
        ->add("username", "text", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add("email", "email", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add("firstname", "text", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add("lastname", "text", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add("middlename", "text", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add('suffix', "text", array( 'attr' => array('readonly' =>'readonly', 'class' => 'form-disabled' )))
        ->add('homeAddress1')
        ->add('homeAddress2')            
        ->add('homeCity')
        ->add('homeState')
        ->add('homeZipCode', 'text', array('pattern'=>'[0-9]{5}', 'attr'=>array( 'maxlength' => '5')))
        ->add('officePhone')
        ->add('fax')
        ->add('cellPhone')
        ->add('npi', 'text', array('pattern'=>'[0-9]{10}', 'attr'=>array( 'maxlength' => '10')))
    ;

}

public function getName()
{
    return 'mho_vmp_physician_profile';
}
```

}

Here is the relevant twig file:

{% extends "FOSUserBundle::layout_landing.html.twig" %}
{% block fos_user_content %}

<form action="{{ path('vmp_physician_profile_edit') }}" {{ form_enctype(form) }} method="POST" class="fos_user_profile_edit">
<div class="container">
    <div class="eight columns">
        <section role="group">
            <header role="columnheader"><span class="head-icon-doctor"></span><h1>{{ 'layout.edit_profile'|trans({}, 'FOSUserBundle') }}</h1></header>
            <article class="clearfix">

                {{ form_errors(form) }}
                {{ form_widget(form._token) }}

                <div class="three-quarters">
                    {{ form_row(form.firstname) }}
                </div>
                <div class="one-quarter">
                    {{ form_row(form.middlename) }}
                </div>
                <div class="three-quarters">
                    {{ form_row(form.lastname) }}
                </div>
                <div class="one-quarter">
                    {{ form_row(form.suffix) }}
                </div>

                 <div class="full-width">
                    {{ form_row(form.username) }}
                 </div>

                 <div class="full-width">
                    {{ form_row(form.email) }}
                 </div>

                <div class="full-width"><hr class="hr-style"></div>

                <div class="one-third-vmp">
                    {{ form_row(form.officePhone) }}
                </div>

                <div class="one-third-vmp">
                    {{ form_row(form.fax) }}
                </div>

                <div class="one-third-vmp">
                    {{ form_row(form.cellPhone) }}
                </div>
            </article>
        </section>
    </div>

    <div class="eight columns">
        <section role="group">
            <header role="columnheader"><span class="head-icon-doctor"></span><h1>Continued</h1></header>
            <article class="clearfix">
                <div class="three-quarters">
                    <label>State License Number</label>
                    <input type="text">
                </div>
                <div class="one-quarter">
                    <label>State</label>
                    <select name="state">
                        <option value="AL">AL</option>
                        <option value="AK">AK</option>
                        <option value="AZ">AZ</option>
                        <option value="AR">AR</option>
                        <option value="CA">CA</option>
                        <option value="CO">CO</option>
                        <option value="CT">CT</option>
                        <option value="DE">DE</option>
                        <option value="DC">DC</option>
                        <option value="FL">FL</option>
                        <option value="GA">GA</option>
                        <option value="HI">HI</option>
                        <option value="ID">ID</option>
                        <option value="IL">IL</option>
                        <option value="IN">IN</option>
                        <option value="IA">IA</option>
                        <option value="KS">KS</option>
                        <option value="KY">KY</option>
                        <option value="LA">LA</option>
                        <option value="ME">ME</option>
                        <option value="MD">MD</option>
                        <option value="MA">MA</option>
                        <option value="MI">MI</option>
                        <option value="MN">MN</option>
                        <option value="MS">MS</option>
                        <option value="MO">MO</option>
                        <option value="MT">MT</option>
                        <option value="NE">NE</option>
                        <option value="NV">NV</option>
                        <option value="NH">NH</option>
                        <option value="NJ">NJ</option>
                        <option value="NM">NM</option>
                        <option value="NY">NY</option>
                        <option value="NC">NC</option>
                        <option value="ND">ND</option>
                        <option value="OH">OH</option>
                        <option value="OK">OK</option>
                        <option value="OR">OR</option>
                        <option value="PA">PA</option>
                        <option value="RI">RI</option>
                        <option value="SC">SC</option>
                        <option value="SD">SD</option>
                        <option value="TN">TN</option>
                        <option value="TX">TX</option>
                        <option value="UT">UT</option>
                        <option value="VT">VT</option>
                        <option value="VA">VA</option>
                        <option value="WA">WA</option>
                        <option value="WV">WV</option>
                        <option value="WI">WI</option>
                        <option value="WY">WY</option>
                    </select>
                </div>

                <div class="full-width">
                    <label>NPI Number <a href="/" class="help-link">Use NPI lookup</a></label>
                    {{ form_widget(form.npi) }}
                </div>

                <div class="full-width"><hr class="hr-style"></div>

                <div class="full-width">
                    {{ form_row(form.homeAddress1) }}
                </div>

                <div class="full-width">
                    {{ form_row(form.homeAddress2) }}
                </div>

                <div class="one-third-vmp">
                    {{ form_row(form.homeCity) }}
                </div>

                <div class="one-third-vmp">
                    {{ form_row(form.homeState) }}
                </div>

                <div class="one-third-vmp">
                    {{ form_row(form.homeZipCode) }}
                </div>

                <div class="full-width"><hr class="hr-style"></div>

                <div class="full-width">
                    {{ form_widget(form) }}
                </div>
                <div class="full-width">
                    <a href="{{ path("mho_vmp_landing") }}">Cancel changes</a>
                    <input class="button matte-blue pull-right" type="submit" value="{{ 'profile.edit.submit'|trans({}, 'FOSUserBundle') }}" />
                </div>
            </article>
        </section>
    </div>
</div>
</form>   

{% endblock fos_user_content %}

And here is my config.yml:

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MHO\VmpBundle\Entity\VmpUser
    service:
        user_manager: nmn_user_manager
    registration:
        confirmation:
            enabled: false
        form:
            handler: nmn_user_registration_form_handler
    profile:
        form:
            handler: nmn_user_profile_form_handler

parameters:
  nmn_user_discriminator_parameters:
    classes:
        vmp_physician:
            entity: MHO\VmpBundle\Entity\VmpPhysician
            registration: MHO\VmpBundle\Form\Type\RegistrationVmpPhysicianFormType
            registration_options: 
                validation_groups: [Registration, Default]
            profile: MHO\VmpBundle\Form\Type\ProfileVmpPhysicianFormType
            profile_options:
                validation_groups: [Profile, Default]
            factory:
        vmp_patient:
            entity: MHO\VmpBundle\Entity\VmpPatient
            registration: MHO\VmpBundle\Form\Type\RegistrationVmpPatientFormType
            profile: MHO\VmpBundle\Form\Type\ProfileVmpPatientFormType
            factory:
        vmp_manager:
            entity: MHO\VmpBundle\Entity\VmpManager
            registration: MHO\VmpBundle\Form\Type\RegistrationVmpManagerFormType
            profile: MHO\VmpBundle\Form\Type\ProfileVmpManagerFormType
            factory:

So what happens is that the form_row(form.firstname) doesnt populate the form with data. The only form field that has any value is the form._token.

Any ideas?

**Comment by leopro** [comment]
The development has **moved to a [new repository](https://github.com/PUGX/PUGXMultiUserBundle)**.
