### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by nucleartux** [netmeansnet/NmnMultiUserBundle#5]
I've already registered your bundle on Packagist.com. Please register on site and tell me your nickname, I will give you the rights to manage the bundle.
Thx for your bundle :)

**Comment by leopro** [comment]
as soon I have a bit of time, I will surely ;)

**Comment by leopro** [comment]
Hi nucleartux my nick is leopro

**Comment by nucleartux** [comment]
You added to maintainers. Currently packagist doesn't allow to delete maintainers, or re-create packages with same name. As soon as possible I will remove myself.
