### ISSUE TITLE
There is no user provider for user "Acme\UserBundle\Entity\UserTwo

### ISSUE THREAD

**Issue by Sydney-o9** [netmeansnet/NmnMultiUserBundle#6]
Hi, 

I have this error message:

There is no user provider for user "Acme\UserBundle\Entity\UserTwo

Cheers, 

Sydney

**Comment by Sydney-o9** [comment]
No problem for user "Acme\UserBundle\Entity\UserTwo.

**Comment by mjuchli** [comment]
Hey I get the same message until I delete my browser cache!

How did you fix?

**Comment by Sydney-o9** [comment]
Hey buddy,

Sorry for the late reply. I was pretty busy.

You need to set persist to true, I guess we should do a PR, but I couldn't bother at the time:

//Acme\UserBundle\Controller\UserOneRegistrationController
$discriminator->setClass('Acme\UserBundle\Entity\UserOne', $persist = true);

you will need to do the same for user two.

To get this, you can have a look at the method setClass() in the discriminator. $persist is set to false by default, which I think is not really good. Meaning userOne will be persisted even though userTwo is logged in. 

Have a look, and let me know if you find a better way to do it.

**Comment by leopro** [comment]
@Sydney-o9 the class is persisted only in UserDiscriminator::onSecurityInteractiveLogin and UserDiscriminator::onSecurityManualLogin when the user is logged in.

**Comment by Sydney-o9** [comment]
Thanks @leonardo-proietti . Just wondering, when the user registers, is onSecurityInteractiveLogin or onSecurityManualLogin triggered upon a succesfull registration? I just didn't understand this issue and solved it this way. Can you confirm that we are doing this correctly? 
This error is only triggered during registration. Is $persist=true the way to go? Many thanks

**Comment by leopro** [comment]
Do you have a registration without email confirmation?

**Comment by Sydney-o9** [comment]
Yes.

**Comment by Sydney-o9** [comment]
I see what you mean. The problem only appears when email confirmation is disabled. Well done!

**Comment by leopro** [comment]
It was a bug already fixed; and now I fixed a similar bug in RegistrationController::confirmAction
