### ISSUE TITLE
Wrong file path in documentation

### ISSUE THREAD

**Issue by pppdns** [netmeansnet/NmnMultiUserBundle#8]
The path 
    # Acme/UserBundle/Resources/config/config.yml

should be
    # app/config/config.yml

in the following section:

https://github.com/netmeansnet/NmnMultiUserBundle/blob/master/Resources/doc/index.md#7-configure-parameters-for-userdiscriminator

see this question:
http://stackoverflow.com/questions/11369894/symfony2-parameternotfoundexception/11374149#comment14995120_11374149

**Comment by leopro** [comment]
As soon as possible I will check, but in all our projects the config is as in the doc.

**Comment by leopro** [comment]
did you import UserBundle\Resources\config\config.yml in app/config/config.yml?
