### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by Sydney-o9** [netmeansnet/NmnMultiUserBundle#9]
Hi, the validation is not working properly.

Try doing this:
1/ register one UserOneType
2/ register one UserTwoType
3/ edit the profile of UserOneType with the username of UserTwoType.

SQLSTATE[23000]: Integrity constraint violation.

Do you have any ideas what the problem is?

**Comment by Sydney-o9** [comment]
This is a recent problem. I went back to a previous backup and the validation was working. This means that this has to be a new change in either FOS User Bundle (which I doubt from what I have checked), but rather a change in the form component, and especially validation.
They have done quite a lot of changes in the form component recently.

Please guys, I need a hand, this bundle is quite important :-)

**Comment by leopro** [comment]
https://github.com/netmeansnet/NmnMultiUserBundle/pull/7#issuecomment-7354291
